"""Daily CROSS MALL inventory reconciliation CLI (Phase 1-B F1.8).

Reads CROSS MALL's variant-level inventory CSV
(`inventory_information.csv` from CROSS MALL > CSV処理 > ダウンロード),
aggregates per master `商品コード`, compares against the central DB's
`inventory_snapshots`, and starts a ReconcileRun with the resulting diffs.

Per client decision D-7, the CSV used in staging is a dummy generated by
us; the production CLI is intended to be triggered by Cloud Scheduler
against the actual CROSS MALL export.

After diff detection the run lands in `pending_approval` state; the
operator reviews the diffs in the admin UI (F3.2), approves or skips each
one, and finalizes. Per D-6, channel pushes are NOT triggered from this
CLI — they are batched once finalize_run returns, by a separate step.

Usage:
    py -m app.cli.reconcile_inventory \\
        --csv csv_file/inventory_information.csv \\
        [--triggered-by cloud_scheduler] \\
        [--dry-run]
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import sys
from collections import defaultdict
from collections.abc import Iterator
from pathlib import Path

from sqlalchemy import select

from app.db import async_session_factory
from app.logging import configure_logging, get_logger
from app.models import InventorySnapshot, MasterSku
from app.services.reconcile import DiffInput, ReconcileService

log = get_logger(__name__)
ENC = "cp932"

# Columns produced by CROSS MALL's inventory CSV export.
COL_PRODUCT_CODE = "商品コード"
COL_QTY = "在庫数量"


def aggregate_csv_by_product(path: Path) -> dict[str, int]:
    """Aggregate the variant-level rows up to the master 商品コード level.

    CROSS MALL's inventory CSV has one row per (商品コード x 属性1 x 属性2),
    while our central DB tracks at the product level. Sum the variant
    quantities per product code so we have a single target per master_sku.
    """
    agg: dict[str, int] = defaultdict(int)
    with path.open("r", encoding=ENC, newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        code_idx = header.index(COL_PRODUCT_CODE)
        qty_idx = header.index(COL_QTY)
        for row in reader:
            if len(row) <= max(code_idx, qty_idx):
                continue
            code = row[code_idx].strip()
            raw = row[qty_idx].strip()
            if not code or not raw:
                continue
            try:
                agg[code] += int(raw)
            except ValueError:
                log.warning(
                    "reconcile.csv.unparseable_qty",
                    code=code,
                    raw=raw,
                )
    return dict(agg)


async def collect_diffs(
    csv_aggregates: dict[str, int],
) -> tuple[list[DiffInput], dict[str, int]]:
    """Compare CROSS MALL aggregates against current snapshots.

    Returns the list of DiffInputs to pass to ReconcileService, plus a
    summary dict for logging.
    """
    summary = {
        "csv_unique_codes": len(csv_aggregates),
        "csv_codes_not_in_master": 0,
        "matched_sku_count": 0,
        "actual_diffs": 0,
    }
    diffs: list[DiffInput] = []

    async with async_session_factory() as session:
        # Pull all master_skus that match csv codes; then their snapshots.
        codes = list(csv_aggregates.keys())
        if not codes:
            return diffs, summary

        masters_result = await session.execute(
            select(MasterSku.id, MasterSku.sku_code).where(MasterSku.sku_code.in_(codes))
        )
        code_to_master_id: dict[str, int] = {code: mid for mid, code in masters_result.all()}
        summary["matched_sku_count"] = len(code_to_master_id)
        summary["csv_codes_not_in_master"] = len(csv_aggregates) - len(code_to_master_id)

        if code_to_master_id:
            snapshots_result = await session.execute(
                select(
                    InventorySnapshot.master_sku_id,
                    InventorySnapshot.on_hand_qty,
                ).where(InventorySnapshot.master_sku_id.in_(list(code_to_master_id.values())))
            )
            # Typed dict-comp keeps mypy happy where dict(Result.all()) has a
            # Row vs tuple incompatibility.
            id_to_current: dict[int, int] = {mid: q for mid, q in snapshots_result.all()}  # noqa: C416
        else:
            id_to_current = {}

        for code, target_qty in csv_aggregates.items():
            master_id = code_to_master_id.get(code)
            if master_id is None:
                continue
            current_qty = id_to_current.get(master_id, 0)
            if current_qty == target_qty:
                continue
            diffs.append(
                DiffInput(
                    master_sku_id=master_id,
                    current_qty=current_qty,
                    target_qty=target_qty,
                )
            )
        summary["actual_diffs"] = len(diffs)
    return diffs, summary


def _diff_iter(diffs: list[DiffInput]) -> Iterator[DiffInput]:
    yield from diffs


async def run(
    csv_path: Path,
    *,
    triggered_by: str = "cloud_scheduler",
    dry_run: bool = False,
) -> int:
    log.info("reconcile.cli.start", csv=str(csv_path), triggered_by=triggered_by, dry_run=dry_run)
    # Sync stat is acceptable here; we run as a one-shot CLI and Path.exists()
    # returns immediately. Switching to anyio.Path would only add a dependency.
    if not csv_path.exists():  # noqa: ASYNC240
        log.error("reconcile.cli.csv_not_found", csv=str(csv_path))
        return 2

    csv_aggregates = aggregate_csv_by_product(csv_path)
    log.info("reconcile.cli.csv_loaded", row_count=len(csv_aggregates))

    diffs, summary = await collect_diffs(csv_aggregates)
    log.info("reconcile.cli.summary", **summary)

    if dry_run:
        log.info("reconcile.cli.dry_run", proposed_diff_count=len(diffs))
        return 0

    async with async_session_factory() as session, session.begin():
        svc = ReconcileService(session)
        run_row = await svc.start_run(
            source="cross_mall_csv",
            triggered_by=triggered_by,
            diffs=_diff_iter(diffs),
            csv_filename=csv_path.name,
        )
    log.info(
        "reconcile.cli.run_created",
        run_id=run_row.id,
        status=run_row.status,
        diff_count=run_row.diff_count,
    )
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Reconcile central DB against CROSS MALL inventory CSV.",
    )
    parser.add_argument(
        "--csv",
        required=True,
        type=Path,
        help="Path to CROSS MALL inventory CSV (CP932).",
    )
    parser.add_argument(
        "--triggered-by",
        default="cloud_scheduler",
        help="Identifier persisted on the ReconcileRun (default: cloud_scheduler).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute and log the diff summary without persisting a ReconcileRun.",
    )
    args = parser.parse_args()
    configure_logging("INFO")
    sys.exit(
        asyncio.run(
            run(
                args.csv,
                triggered_by=args.triggered_by,
                dry_run=args.dry_run,
            )
        )
    )


if __name__ == "__main__":
    main()
