"""Daily CROSS MALL inventory reconciliation CLI (Phase 1-B F1.8).

Reads CROSS MALL's variant-level stock CSV (商品コード x 属性1 x 属性2 x 在庫数量),
keys each row as '{商品コード}|{color}|{size}', matches it to a VARIANT master via
the channel='crossmall' mappings (created by import_variant_mappings, alias-safe),
sums aliases per master, excludes is_bundle parents (derived stock), compares
against `inventory_snapshots`, and starts a ReconcileRun with the resulting diffs.

Per client decision D-7, the CSV used in staging is a dummy generated by
us; the production CLI is intended to be triggered by Cloud Scheduler
against the actual CROSS MALL export.

After diff detection the run lands in `pending_approval` state; the
operator reviews the diffs in the admin UI (F3.2), approves or skips each
one, and finalizes. Per D-6, channel pushes are NOT triggered from this
CLI — they are batched once finalize_run returns, by a separate step.

Usage:
    py -m app.cli.reconcile_inventory \\
        --csv csv_file/inventory_information.csv \\
        [--triggered-by cloud_scheduler] \\
        [--dry-run]
"""

from __future__ import annotations

import argparse
import asyncio
import csv
import sys
import tempfile
from collections import defaultdict
from collections.abc import Iterator
from pathlib import Path

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.cli.build_channel_mapping import extract_color, extract_size
from app.cli.import_variant_mappings import crossmall_key
from app.db import async_session_factory
from app.logging import configure_logging, get_logger
from app.models import ChannelSkuMapping, InventorySnapshot, MasterSku
from app.services.reconcile import DiffInput, ReconcileService

GS_PREFIX = "gs://"

# A factory that produces async sessions. Defaults to the production
# async_session_factory; tests override with a factory bound to the test
# engine so the same connection sees both fixture-seeded data and the
# CLI's reads/writes.
SessionFactory = async_sessionmaker[AsyncSession]

log = get_logger(__name__)
ENC = "cp932"

# Columns produced by CROSS MALL's inventory CSV export.
COL_PRODUCT_CODE = "商品コード"
COL_QTY = "在庫数量"
COL_ATTR1 = "属性１名"
COL_ATTR2 = "属性２名"


def _download_gs(uri: str) -> Path:
    """Download a `gs://bucket/object` URI to a local temp file.

    Lives in a separate function so tests can monkeypatch this entry point
    without pulling google-cloud-storage into the test runtime.
    """
    bucket_name, _, blob_name = uri[len(GS_PREFIX) :].partition("/")
    if not bucket_name or not blob_name:
        raise ValueError(f"malformed gs:// URI: {uri!r}")
    from google.cloud import storage  # type: ignore

    client = storage.Client()
    blob = client.bucket(bucket_name).blob(blob_name)
    tmp = tempfile.NamedTemporaryFile(  # noqa: SIM115
        delete=False,
        suffix=Path(blob_name).suffix or ".csv",
    )
    tmp.close()
    blob.download_to_filename(tmp.name)
    return Path(tmp.name)


def resolve_csv_arg(csv_arg: str | Path) -> Path:
    """Normalize the `--csv` argument to a local `Path`.

    Plain paths pass through. `gs://bucket/object` URIs are downloaded to
    a temp file (its lifecycle is the process lifetime — Cloud Run Jobs
    are one-shot so the file is collected when the container exits).
    """
    raw = str(csv_arg)
    if raw.startswith(GS_PREFIX):
        return _download_gs(raw)
    return Path(raw)


def aggregate_csv_variants(path: Path) -> dict[str, int]:
    """Read the CROSS MALL stock CSV into {crossmall_key: qty}, one key per
    VARIANT — crossmall_key = '{商品コード}|{color}|{size}', with color/size
    normalized exactly as the channel='crossmall' mappings were built, so daily
    reconcile matches on a single stock CSV (no token computation here).
    """
    agg: dict[str, int] = defaultdict(int)
    with path.open("r", encoding=ENC, newline="") as f:
        reader = csv.reader(f)
        header = next(reader)
        code_idx = header.index(COL_PRODUCT_CODE)
        qty_idx = header.index(COL_QTY)
        a1_idx = header.index(COL_ATTR1) if COL_ATTR1 in header else None
        a2_idx = header.index(COL_ATTR2) if COL_ATTR2 in header else None
        for row in reader:
            if len(row) <= max(code_idx, qty_idx):
                continue
            code = row[code_idx].strip()
            raw = row[qty_idx].strip()
            if not code or not raw:
                continue
            attr1 = row[a1_idx].strip() if a1_idx is not None and len(row) > a1_idx else ""
            attr2 = row[a2_idx].strip() if a2_idx is not None and len(row) > a2_idx else ""
            color = extract_color(attr1, attr2)
            size = extract_size(attr2, attr1)
            try:
                agg[crossmall_key(code, color, size)] += int(raw)
            except ValueError:
                log.warning("reconcile.csv.unparseable_qty", code=code, raw=raw)
    return dict(agg)


async def collect_diffs(
    csv_aggregates: dict[str, int],
    session: AsyncSession,
) -> tuple[list[DiffInput], dict[str, int]]:
    """Match the stock CSV's crossmall keys to VARIANT masters via the
    channel='crossmall' mappings, sum alias keys per master, exclude is_bundle
    masters (their stock is DERIVED, never reconciled), and diff against
    snapshots.

    Caller owns the session lifecycle (so tests can share the fixture-managed
    transactional session with the CLI).
    """
    summary = {
        "csv_keys": len(csv_aggregates),
        "unmapped_keys": 0,
        "matched_masters": 0,
        "excluded_bundles": 0,
        "actual_diffs": 0,
    }
    if not csv_aggregates:
        return [], summary

    keys = list(csv_aggregates.keys())
    map_result = await session.execute(
        select(ChannelSkuMapping.channel_sku, ChannelSkuMapping.master_sku_id).where(
            ChannelSkuMapping.channel == "crossmall",
            ChannelSkuMapping.channel_sku.in_(keys),
            ChannelSkuMapping.is_active.is_(True),
        )
    )
    key_to_master: dict[str, int] = {cs: mid for cs, mid in map_result.all()}  # noqa: C416
    summary["unmapped_keys"] = len(csv_aggregates) - len(key_to_master)

    # Alias 商品コード map to the same variant master — sum their target qty.
    target_by_master: dict[int, int] = defaultdict(int)
    for key, qty in csv_aggregates.items():
        master_id = key_to_master.get(key)
        if master_id is not None:
            target_by_master[master_id] += qty

    # Defensively drop any is_bundle master (crossmall mappings already skip
    # them, but never reconcile a derived-availability parent).
    if target_by_master:
        bundle_result = await session.execute(
            select(MasterSku.id).where(
                MasterSku.id.in_(list(target_by_master.keys())),
                MasterSku.is_bundle.is_(True),
            )
        )
        for (bundle_id,) in bundle_result.all():
            target_by_master.pop(bundle_id, None)
            summary["excluded_bundles"] += 1
    summary["matched_masters"] = len(target_by_master)

    diffs: list[DiffInput] = []
    if target_by_master:
        snap_result = await session.execute(
            select(InventorySnapshot.master_sku_id, InventorySnapshot.on_hand_qty).where(
                InventorySnapshot.master_sku_id.in_(list(target_by_master.keys()))
            )
        )
        id_to_current: dict[int, int] = {mid: q for mid, q in snap_result.all()}  # noqa: C416
        for master_id, target_qty in target_by_master.items():
            current_qty = id_to_current.get(master_id, 0)
            if current_qty != target_qty:
                diffs.append(
                    DiffInput(
                        master_sku_id=master_id,
                        current_qty=current_qty,
                        target_qty=target_qty,
                    )
                )
    summary["actual_diffs"] = len(diffs)
    return diffs, summary


def _diff_iter(diffs: list[DiffInput]) -> Iterator[DiffInput]:
    yield from diffs


async def run(
    csv_path: Path | str,
    *,
    triggered_by: str = "cloud_scheduler",
    dry_run: bool = False,
    session_factory: SessionFactory | None = None,
) -> int:
    """Top-level CLI entry. `session_factory` defaults to the production
    `async_session_factory`; tests pass in a factory bound to the test
    engine so the fixture-seeded data is visible to the CLI.

    `csv_path` accepts a local path or a `gs://bucket/object` URI; gs:// URIs
    are downloaded to a temp file before reading.
    """
    factory = session_factory or async_session_factory
    log.info("reconcile.cli.start", csv=str(csv_path), triggered_by=triggered_by, dry_run=dry_run)
    try:
        local_path = resolve_csv_arg(csv_path)
    except (ValueError, OSError) as exc:
        log.error("reconcile.cli.csv_resolve_failed", csv=str(csv_path), error=str(exc))
        return 2
    # Sync stat is acceptable here; we run as a one-shot CLI and Path.exists()
    # returns immediately. Switching to anyio.Path would only add a dependency.
    if not local_path.exists():
        log.error("reconcile.cli.csv_not_found", csv=str(local_path))
        return 2

    csv_aggregates = aggregate_csv_variants(local_path)
    log.info("reconcile.cli.csv_loaded", variant_keys=len(csv_aggregates))

    async with factory() as read_session:
        diffs, summary = await collect_diffs(csv_aggregates, read_session)
    log.info("reconcile.cli.summary", **summary)

    if dry_run:
        log.info("reconcile.cli.dry_run", proposed_diff_count=len(diffs))
        return 0

    async with factory() as session, session.begin():
        svc = ReconcileService(session)
        run_row = await svc.start_run(
            source="cross_mall_csv",
            triggered_by=triggered_by,
            diffs=_diff_iter(diffs),
            csv_filename=local_path.name,
        )
    log.info(
        "reconcile.cli.run_created",
        run_id=run_row.id,
        status=run_row.status,
        diff_count=run_row.diff_count,
    )
    return 0


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Reconcile central DB against CROSS MALL inventory CSV.",
    )
    parser.add_argument(
        "--csv",
        required=True,
        type=str,
        help="Path to CROSS MALL inventory CSV (CP932). "
        "Accepts a local path or a gs://bucket/object URI.",
    )
    parser.add_argument(
        "--triggered-by",
        default="cloud_scheduler",
        help="Identifier persisted on the ReconcileRun (default: cloud_scheduler).",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Compute and log the diff summary without persisting a ReconcileRun.",
    )
    args = parser.parse_args()
    configure_logging("INFO")
    sys.exit(
        asyncio.run(
            run(
                args.csv,
                triggered_by=args.triggered_by,
                dry_run=args.dry_run,
            )
        )
    )


if __name__ == "__main__":
    main()
