# Run Alembic migrations on the production Cloud SQL instance via the
# Cloud SQL Auth Proxy. This connects locally over the proxy on 5433 to
# avoid colliding with a local Postgres on 5432.
#
#   ./scripts/run_db_migration.ps1

$ErrorActionPreference = "Stop"

$PROJECT_ID = "inventory-496204"
$REGION     = "asia-northeast1"
$INSTANCE   = "product-system"
$DB         = "product_system"
$LOCAL_PORT = 5433

$CONN_NAME = "${PROJECT_ID}:${REGION}:${INSTANCE}"

# Read the db_password generated by Terraform from tfvars.
$tfvars = Get-Content "infra/terraform/terraform.tfvars" -Raw
$DB_PASSWORD = ([regex]'db_password\s*=\s*"([^"]+)"').Match($tfvars).Groups[1].Value
if (-not $DB_PASSWORD) { throw "Could not read db_password from terraform.tfvars" }

Write-Host "==> Downloading Cloud SQL Auth Proxy (one-time)..."
$proxyDir = ".local/cloud-sql-proxy"
New-Item -ItemType Directory -Path $proxyDir -Force | Out-Null
if (-not (Test-Path "$proxyDir/cloud-sql-proxy.exe")) {
    Invoke-WebRequest `
        -Uri "https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.13.0/cloud-sql-proxy.x64.exe" `
        -OutFile "$proxyDir/cloud-sql-proxy.exe" `
        -UseBasicParsing
}

Write-Host "==> Starting Cloud SQL Auth Proxy on port $LOCAL_PORT..."
$proxy = Start-Process -PassThru -NoNewWindow `
    -FilePath "$proxyDir/cloud-sql-proxy.exe" `
    -ArgumentList @("$CONN_NAME", "--port=$LOCAL_PORT")

try {
    Start-Sleep -Seconds 5

    Write-Host "==> Running Alembic upgrade..."
    $env:DATABASE_URL_SYNC = "postgresql+psycopg2://postgres:${DB_PASSWORD}@127.0.0.1:${LOCAL_PORT}/$DB"
    py -m alembic upgrade head

    Write-Host "`nMigration complete. Production DB is now on schema 0002."
}
finally {
    Write-Host "==> Stopping Cloud SQL Auth Proxy..."
    Stop-Process -Id $proxy.Id -Force -ErrorAction SilentlyContinue
}
